/*******************************************************************************
* FILE NAME: CarView.hpp                                                       *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     CarView- Car salesperson application                                     *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _CARVIEW_
#define _CARVIEW_  

class CarView;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

class IMultiCellCanvas;
class IStaticText;
class IEntryField;
class IPushButton;
class Car;
class IDatastore;
class accessError;
class IMessageBox;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

class CarViewConn3;
class CarViewConn2;
class CarViewConn13;
class CarViewConn4;
class CarViewConn5;
class CarViewConn15;
class CarViewConn6;
class CarViewConn7;
class CarViewConn23;
class CarViewConn14;
class CarViewConn16;
class CarViewConn17;
class CarViewConn18;
class CarViewConn19;
class CarViewConn20;
class CarViewConn29;
class CarViewConn30;
class CarViewConn39;
class CarViewConn21;
class CarViewConn9;
class CarViewConn10;
class CarViewConn22;
class CarViewConn32;
class CarViewConn33;
class CarViewConn24;
class CarViewConn25;
class CarViewConn26;
#include "CarView.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for CarView
//*****************************************************************************
class CarView : public IFrameWindow {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   CarView(
      unsigned long id = WND_CarView,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = IFrameWindow::defaultStyle ( ),
      const char* title = defaultTitle());

   virtual  ~CarView();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static IString defaultTitle();
   virtual CarView & initializePart();
   CarView * getFrameWindow() { return this; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   IMultiCellCanvas * iMultiCellCanvas2;
   IStaticText * iStaticText1;
   IStaticText * iStaticText2;
   IStaticText * iStaticText3;
   IStaticText * iStaticText4;
   IStaticText * iStaticText5;
   IEntryField * iEntryField1;
   IEntryField * iEntryField2;
   IEntryField * iEntryField3;
   IEntryField * iEntryField4;
   IEntryField * iEntryField5;
   IPushButton * iPushButton1;
   IPushButton * iPushButton2;
   IPushButton * iPushButton3;
   IPushButton * iPushButton4;
   IPushButton * iPushButton5;
   Car * iCar1;
   IDatastore * iDatastore1;
   accessError * iaccessError1;
   IMessageBox * iMessageBox1;
   CarViewConn3 * conn3;
   CarViewConn2 * conn2;
   CarViewConn13 * conn13;
   CarViewConn4 * conn4;
   CarViewConn5 * conn5;
   CarViewConn15 * conn15;
   CarViewConn6 * conn6;
   CarViewConn7 * conn7;
   CarViewConn23 * conn23;
   CarViewConn14 * conn14;
   CarViewConn16 * conn16;
   CarViewConn17 * conn17;
   CarViewConn18 * conn18;
   CarViewConn19 * conn19;
   CarViewConn20 * conn20;
   CarViewConn29 * conn29;
   CarViewConn30 * conn30;
   CarViewConn39 * conn39;
   CarViewConn21 * conn21;
   CarViewConn9 * conn9;
   CarViewConn10 * conn10;
   CarViewConn22 * conn22;
   CarViewConn32 * conn32;
   CarViewConn33 * conn33;
   CarViewConn24 * conn24;
   CarViewConn25 * conn25;
   CarViewConn26 * conn26;
   static unsigned long partWindowId;

friend class CarViewConn39;

};   //CarView


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
