/*******************************************************************************
* FILE NAME: CarView.h                                                         *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     CarView- Car salesperson application                                     *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_CarView
#define WND_CarView  VBBASEWINDOWID
#endif

#define WNDOFFSET_CarView_FrameWindow  0
#define WND_CarView_FrameWindow  WND_CarView

#define WND_CarView_MultiCellCanvas2  IC_FRAME_CLIENT_ID

#define WNDOFFSET_CarView_StaticText1  1
#define WND_CarView_StaticText1  WND_CarView + WNDOFFSET_CarView_StaticText1

#define WNDOFFSET_CarView_StaticText2  2
#define WND_CarView_StaticText2  WND_CarView + WNDOFFSET_CarView_StaticText2

#define WNDOFFSET_CarView_StaticText3  3
#define WND_CarView_StaticText3  WND_CarView + WNDOFFSET_CarView_StaticText3

#define WNDOFFSET_CarView_StaticText4  4
#define WND_CarView_StaticText4  WND_CarView + WNDOFFSET_CarView_StaticText4

#define WNDOFFSET_CarView_StaticText5  5
#define WND_CarView_StaticText5  WND_CarView + WNDOFFSET_CarView_StaticText5

#define WNDOFFSET_CarView_EntryField1  6
#define WND_CarView_EntryField1  WND_CarView + WNDOFFSET_CarView_EntryField1

#define WNDOFFSET_CarView_EntryField2  7
#define WND_CarView_EntryField2  WND_CarView + WNDOFFSET_CarView_EntryField2

#define WNDOFFSET_CarView_EntryField3  8
#define WND_CarView_EntryField3  WND_CarView + WNDOFFSET_CarView_EntryField3

#define WNDOFFSET_CarView_EntryField4  9
#define WND_CarView_EntryField4  WND_CarView + WNDOFFSET_CarView_EntryField4

#define WNDOFFSET_CarView_EntryField5  10
#define WND_CarView_EntryField5  WND_CarView + WNDOFFSET_CarView_EntryField5

#define WNDOFFSET_CarView_PushButton1  11
#define WND_CarView_PushButton1  WND_CarView + WNDOFFSET_CarView_PushButton1

#define WNDOFFSET_CarView_PushButton2  12
#define WND_CarView_PushButton2  WND_CarView + WNDOFFSET_CarView_PushButton2

#define WNDOFFSET_CarView_PushButton3  13
#define WND_CarView_PushButton3  WND_CarView + WNDOFFSET_CarView_PushButton3

#define WNDOFFSET_CarView_PushButton4  14
#define WND_CarView_PushButton4  WND_CarView + WNDOFFSET_CarView_PushButton4

#define WNDOFFSET_CarView_PushButton5  15
#define WND_CarView_PushButton5  WND_CarView + WNDOFFSET_CarView_PushButton5




#define WNDOFFSET_CarView_MessageBox1  16
#define WND_CarView_MessageBox1  WND_CarView + WNDOFFSET_CarView_MessageBox1


